name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda create --name ytl python==3.10
    - name: Install ytopt and libensemble
      run: |
            conda activate ytl
            pip install scikit-learn==1.0.2
            pip install numpy==1.24.1
            git clone https://github.com/ytopt-team/ConfigSpace.git
            cd ConfigSpace
            pip install .
            cd ..
            python -c "import ConfigSpace as CS; print(dir(CS)); print('1'); print(CS.__path__); print('2');"
            python -c "import ConfigSpace as CS; CS.ConfigurationSpace()"
            git clone https://github.com/ytopt-team/scikit-optimize.git
            cd scikit-optimize
            pip install .
            cd ..
            git clone -b version1 https://github.com/ytopt-team/autotune.git
            cd autotune
            pip install .
            cd ..
            git clone https://github.com/ytopt-team/ytopt.git
            cd ytopt
            pip install .
            cd ..
            git clone https://github.com/ytopt-team/libensemble.git
            cd libensemble
            pip install .
            cd ..
    - name: Test with ytopt
      run: |
        cd ytopt/ytopt/benchmark/xsbench-omp/xsbench
        chmod +x run.bat
        ./run.bat
